### ISSUE TITLE
How to translate ?

### ISSUE THREAD

**Issue by ybabel** [nouchka/docker-hackmyresume-web#1]
Great container. It's working fine. But I'm french and I did not found a way to translate titles of my resume.
The generated page is a mixture of english and french.
Is there a way to translate : About,  Work Experience, Skills (and so on) ?

**Comment by ybabel** [comment]
I figured out that I could change the template file. But how can I use my own ? do I have to publish it in "node" (I'm not familiar with nodejs) or can I use a template that I put in my github repository ?

**Comment by nouchka** [comment]
Hi,

sorry for my late answer; french here too :)
I will work on it this afternoon: I will add the possibility to specify a git repository as a theme, without the need to publish it as a node module, etc... I hope a git clone in the right directory will do the trick

**Comment by ybabel** [comment]
great :-)

**Comment by nouchka** [comment]
just updated docker images: I added a TEMPLATE_GIT env parameters.
The docker-compose file is updated and is working

**Comment by ybabel** [comment]
It worked. Thanks.
